apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-04-28T15:43:29Z"
  generateName: space06-1-lotus-
  labels:
    app: lotus-node-appUPDATE
    chart: filecoin-0.3.5
    controller-revision-hash: space06-1-lotus-dd96dcd8
    heritage: Helm
    release: space06
    release-fork: space06-1
    statefulset.kubernetes.io/pod-name: space06-1-lotus-0
  name: space06-1-lotus-0
  namespace: spacerace
  resourceVersion: "166126257"
  selfLink: /api/v1/namespaces/spacerace/pods/space06-1-lotus-0
  uid: 6164a385-ec65-4f29-adc9-3cfe651ad725
spec:
  containers:
  - command:
    - /etc/lotus/docker/run
    env:
    - name: INFRA_LOTUS_DAEMON
      value: "true"
    - name: INFRA_LOTUS_HOME
      value: /home/lotus_user
    - name: INFRA_CLEAR_RESTART
      value: "true"
    - name: INFRA_IMPORT_SNAPSHOT
      value: "true"
    - name: SNAPSHOTURL
      value: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
    - name: INFRA_SYNC
      value: "true"
    - name: INFRA_SECRETVOLUME
      value: "true"
    - name: NETWORK
      value: mainnet
    image: glif/lotus:v1.8.0
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - rm -f $INFRA_LOTUS_HOME/.lotus/sync-complete
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: api
      timeoutSeconds: 10
    name: filecoin
    ports:
    - containerPort: 1234
      name: api
      protocol: TCP
    - containerPort: 1235
      name: p2p
      protocol: TCP
    resources:
      limits:
        cpu: "15"
        memory: 120Gi
      requests:
        cpu: "7"
        memory: 60Gi
    startupProbe:
      exec:
        command:
        - cat
        - /home/lotus_user/.lotus/import-complete
      failureThreshold: 200
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /keystore
      name: lotus-secret-vol
    - mountPath: /home/lotus_user/.lotus
      name: vol-lotus
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-khpg8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: space06-1-lotus-0
  initContainers:
  - args:
    - chown -R 2000:2000 /tmp;
    command:
    - /bin/sh
    - -c
    image: busybox
    imagePullPolicy: Always
    name: hostpath-permission
    resources: {}
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: vol-lotus
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-khpg8
      readOnly: true
  nodeName: ip-192-168-14-115.us-east-2.compute.internal
  nodeSelector:
    aws.amazon.com/eks-local-ssd: "true"
    lifecycle: Ec2Spot-i3-2x4x
    role: worker
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsUser: 2000
  serviceAccount: default
  serviceAccountName: default
  subdomain: space06-lotus-service
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: lotus-secret-vol
    secret:
      defaultMode: 384
      secretName: space06-1-lotus-secret
  - hostPath:
      path: /nvme/disk/lotus
      type: DirectoryOrCreate
    name: vol-lotus
  - name: default-token-khpg8
    secret:
      defaultMode: 420
      secretName: default-token-khpg8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-28T15:43:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-28T15:44:55Z"
    message: 'containers with unready status: [filecoin]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-28T15:44:55Z"
    message: 'containers with unready status: [filecoin]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-28T15:43:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d05953715e7a9d860d2bc68db633d67b4b07a0635ab9ab8673b31321380eb644
    image: glif/lotus:v1.8.0
    imageID: docker-pullable://glif/lotus@sha256:b9a71c3a61105975b931682959474245509dee13ff3261225acbd926b4dbe130
    lastState:
      terminated:
        containerID: docker://f58f2253f1c5204bdb1424496d4630032c1c5abc125660c14110d6adb589ee27
        exitCode: 137
        finishedAt: "2021-04-28T15:44:53Z"
        reason: Error
        startedAt: "2021-04-28T15:43:46Z"
    name: filecoin
    ready: false
    restartCount: 1
    started: false
    state:
      running:
        startedAt: "2021-04-28T15:44:54Z"
  hostIP: 192.168.14.115
  initContainerStatuses:
  - containerID: docker://a561b71fd42d2fb966e53e59d22db866ed95639713c924e067a41e3b8b8716d2
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
    lastState: {}
    name: hostpath-permission
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://a561b71fd42d2fb966e53e59d22db866ed95639713c924e067a41e3b8b8716d2
        exitCode: 0
        finishedAt: "2021-04-28T15:43:35Z"
        reason: Completed
        startedAt: "2021-04-28T15:43:34Z"
  phase: Running
  podIP: 192.168.20.175
  podIPs:
  - ip: 192.168.20.175
  qosClass: Burstable
  startTime: "2021-04-28T15:43:29Z"
