apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-04-09T21:34:39Z"
  generateName: space06-lotus-
  labels:
    app: lotus-node-app
    chart: filecoin-0.3.4
    controller-revision-hash: space06-lotus-7665db694c
    heritage: Helm
    release: space06
    statefulset.kubernetes.io/pod-name: space06-lotus-0
  name: space06-lotus-0
  namespace: spacerace
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: space06-lotus
    uid: 53903531-d3c8-4b7a-83b3-58936a3a766d
  resourceVersion: "159136186"
  selfLink: /api/v1/namespaces/spacerace/pods/space06-lotus-0
  uid: c3c03bfa-c4ed-402a-9105-223e77cde86a
spec:
  containers:
  - command:
    - /etc/lotus/docker/run
    env:
    - name: INFRA_LOTUS_DAEMON
      value: "true"
    - name: INFRA_LOTUS_HOME
      value: /home/lotus_user
    - name: INFRA_CLEAR_RESTART
      value: "true"
    - name: INFRA_IMPORT_SNAPSHOT
      value: "true"
    - name: SNAPSHOTURL
      value: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
    - name: INFRA_SYNC
      value: "true"
    - name: INFRA_SECRETVOLUME
      value: "true"
    - name: NETWORK
      value: mainnet
    image: glif/lotus:v1.6.0
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - rm -f $INFRA_LOTUS_HOME/.lotus/sync-complete
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: api
      timeoutSeconds: 10
    name: filecoin
    ports:
    - containerPort: 1234
      name: api
      protocol: TCP
    - containerPort: 1235
      name: p2p
      protocol: TCP
    resources:
      limits:
        cpu: "15"
        memory: 120Gi
      requests:
        cpu: "12"
        memory: 64Gi
    startupProbe:
      exec:
        command:
        - cat
        - /home/lotus_user/.lotus/import-complete
      failureThreshold: 200
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /keystore
      name: lotus-secret-vol
    - mountPath: /home/lotus_user/.lotus
      name: vol-lotus
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-khpg8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: space06-lotus-0
  nodeName: ip-192-168-84-151.us-east-2.compute.internal
  nodeSelector:
    assignedPod: space06
    aws.amazon.com/eks-local-ssd: "true"
    lifecycle: OnDemand
    role: worker
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsUser: 2000
  serviceAccount: default
  serviceAccountName: default
  subdomain: space06-lotus-service
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: vol-lotus
    persistentVolumeClaim:
      claimName: vol-lotus-space06-lotus-0
  - name: lotus-secret-vol
    secret:
      defaultMode: 384
      secretName: space06-lotus-secret
  - name: default-token-khpg8
    secret:
      defaultMode: 420
      secretName: default-token-khpg8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-09T21:34:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-09T21:57:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-09T21:57:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-09T21:34:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://07a256419263c2b06e82bdfd25dd6c51d046f4095bc840ce56a641f470f6cbcf
    image: glif/lotus:v1.6.0
    imageID: docker-pullable://glif/lotus@sha256:615efa3735704ad481e2381110eba79e0b4cabeebf5158a17c8eb52cc5e9145e
    lastState: {}
    name: filecoin
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-04-09T21:34:40Z"
  hostIP: 192.168.84.151
  phase: Running
  podIP: 192.168.81.231
  podIPs:
  - ip: 192.168.81.231
  qosClass: Burstable
  startTime: "2021-04-09T21:34:39Z"
