# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nodeSelector:
  enabled: true
  nodeSelectorKey: nodeGroupName
  nodeSelectorValue: noGroup


lotus:
  service:
    enabled: true

image:
  repository: glif/lotus:v1.16.0-calibnet
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use. Will be prefixed with release name
  name: acc

SecurityContext:
  runAsNonRoot: true
  runAsUser: 2000
  runAsGroup: 2000
  fsGroup: 2000

## cache service settings
cache:
  enabled: false
  image: protofire/filecoin-rpc-proxy:0.0.3
  replicas: 2


init:
  sync:
    enabled: true
  importSnapshot:
    enabled: false
  clearRestart:
    enabled: false
  import:
    enabled: false
    # ideally a shared volume containing chain dump
    volume: {}
      #- name: filecoin-chain-vol
      #  persistentVolumeClaim:
      #    claimName: efs-claim

secretVolume:
  enabled: true
  persistNodeID: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  lotus:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: 1900m
      memory: 5Gi
  ipfs:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 3000m
      memory: 3Gi

persistence:
  # If persistence is set to false no persistent volumes will be created
  enabled: true
  hostPath: /nvme/disk
  autoResizer:
    enabled: true
    increaseThreshold: 90 # in %
    increaseStep: 10 # in %
    cron: "0 0 * * *"
  snapshots:
    # If uploadToIpfs is set to true the internal Lotus snapshot will be created and uploaded to the IPFS system. Note that IPFS must be nenabled in that case
    uploadToIpfs:
      enabled: false
      export: hot
      # shedPeriod: 6h
      shareToGist:
        enabled: false
        cron: "0 0 * * *"
        #address: https://gist.github.com/openworklabbot/d03393d1f6e70e089e9e8d18922474f6
        #authorEmail:
        #authorName: Protofire Bot
    # If snapshots are enabled - the PV will be deployed with ebs-sc class unless custom class is specified
    enabled: true
    # If automation is enabled - several CronJobs will be created to create snapshots and/or delete old snapshots automatically.
    automation:
      deletion:
        cron: "0 1 * * *"
        enabled: true
        retention:
          count: 2
      creation:
        cron: "0 0 * * *"
        enabled: true
    # If restore is enabled the snapshot name must be specified. Charts will attempt to find the existing snapshot with this name and create a PV from that snapshot.
    restore:
      enabled: false
      #name: snapshot-blah
  # For each of the deployed services one can specify the disk size, custom disk type and access mode.
  lotus:
    size: "35Gi"
    accessModes:
      - ReadWriteOnce
    storageClassName: "ebs-sc-gp2"
    lotusVolumeName: "vol-lotus"
  ipfs:
    size: "10Gi"
    accessModes:
      - ReadWriteOnce

# Defines whether should be deployed Lotus node with service, gateway or without.
Lotus:
  statefulset:
    enabled: true
  enabled: true
  maxheapsize: false
  service:
    enabled: true
    is_slave: false
    label: some-release
    gateway: false

# Defines remote endpoint for services(StateDiff e.t.c.)
#lotusDNS: some-service

# Defines whether IPFS should be deployed with Lotus node.
IPFS:
  enabled: false

StateDiff:
  enabled: false

tolerations: []

podAntiAffinity:
  enabled: false

healthcheck:
  enabled: true
  readinessProbe: true
  network: calibration
