nodeSelector:
  enabled: true
  nodeLabel:
    lifecycle: Ec2Spot-i3
# powergate, ipfs in api-service mode don't work now. don't enable it.
ingress:
  lotus:
    enabled: false
  ipfs:
    enabled: false
  powergate:
    enabled: false
  statediff:
    enabled: true

Lotus:
  enabled: false
  service:
    enabled: false
Powergate:
  enabled: false
IPFS:
  enabled: false
StateDiff:
  enabled: true

lotusDNS: api-read-dev-lotus-service