persistence:
   enabled: false

SecurityContext:
  runAsNonRoot: false
ingress:
  lotus:
    enabled: false
  statediff:
    enabled: true

resources:
  statediff:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 7500m
      memory: 12Gi

Lotus:
  enabled: false
  service:
    enabled: false
StateDiff:
  enabled: true

lotusDNS: api-read-lotus-service

persistence:
  enabled: false
  snapshots:
    automation:
      deletion:
        enabled: false
      creation:
        enabled: false
