ingress:
  lotus:
    enabled: false
  statediff:
    enabled: false

Lotus:
  enabled: false
  service:
    enabled: false

lotusDNS: api-read-lotus-service

persistence:
  enabled: false
  snapshots:
    automation:
      deletion:
        enabled: false
      creation:
        enabled: false

resources:
  statediff:
    requests:
      cpu: 300m
      memory: 3Gi
    limits:
      cpu: 7500m
      memory: 30Gi


SecurityContext:
  runAsNonRoot: false

StateDiff:
  enabled: false
