{{- if .Values.cache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cache-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.client }}-cache
  replicas: {{ .Values.cache.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.client }}-cache
    spec:
      containers:
        - name: {{ .Values.client }}-cache
          image: {{ .Values.cache.image }}
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ .Release.Name }}-config-cache
              mountPath: /home/proxy/config.yaml
              subPath: config.yaml
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 12Gi
              cpu: 5
            requests:
              memory: 4Gi
              cpu: 500m
      volumes:
        - name: {{ .Release.Name }}-config-cache
          secret:
            secretName: {{ .Release.Name }}-{{ .Values.client }}-secret
            items:
              - key: config
                path: config.yaml
      nodeSelector:
      {{ toYaml .Values.cache.nodeSelector.nodeLabel | nindent 8 }}
{{- end }}
