{{- if .Values.ingress.lotus.gateway }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-gateway-lotus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.lotus.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /{{ .Release.Name }}/gw(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-lotus-service
                port:
                  number: 2346
{{- end }}
