{{- if .Values.Powergate.enabled }}
{{- if .Values.ingress.powergate.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-powergate
  annotations:
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.powergate.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:    
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}-powergate-service
              port:
                number: 5002
          path: /{{ .Release.Name }}/powergate/(grpc|5002)(/|$)(.*)
          pathType: Prefix
        - backend:
            service:
              name: {{ .Release.Name }}-powergate-service
              port:
                number: 6002
          path: /{{ .Release.Name }}/powergate/(webproxy|6002)(/|$)(.*)
          pathType: Prefix
        - backend:
            service:
              name: {{ .Release.Name }}-powergate-service
              port:
                number: 6060
          path: /{{ .Release.Name }}/powergate/(6060)(/|$)(.*)
          pathType: Prefix
        - backend:
            service:
              name: {{ .Release.Name }}-powergate-service
              port:
                number: 7000
          path: /{{ .Release.Name }}/powergate/(web|7000)(/|$)
          pathType: Prefix
        - backend:
            service:
              name: {{ .Release.Name }}-powergate-service
              port:
                number: 8889
          path: /{{ .Release.Name }}/powergate/(8889)(/|$)(.*)
          pathType: Prefix
{{- end }}
{{- end }}
