{{- if .Values.StateDiff.enabled }}
{{- if .Values.ingress.statediff.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-statediff
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$4
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.statediff.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:    
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}-statediff-service
              port:
                number: 33333
          path: /{{ .Release.Name }}/statediff(/)?(33333|rpc)?(/|$)?(.*)
          pathType: Prefix
{{- end }}
{{- end }}
