{{- if .Values.ingress.lotus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-lotus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.lotus.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- if .Values.cache.enabled }}
          - path: /{{ .Release.Name }}/cache(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-cache-service
                port:
                  number: 8080
          - path: /{{ .Release.Name }}/lotus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-lotus-service
                port:
                  number: 1234
{{- else }}
          - path: /{{ .Release.Name }}/lotus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-lotus-service
                port:
                  number: 1234
{{- end }}
{{- end }}
