{{- if .Values.isEFS.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.globalParameters.project.name }}-{{ .Values.globalParameters.environment.name }}-{{ .Values.globalParameters.region.shortRegionName }}-{{ .Values.globalParameters.subEnvironment.name }}-efs
  resources:
    requests:
      storage: 5Gi
{{- end }}
