{{- if .Values.createLotusService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lotus-service
  labels:
    {{- range $key, $value := .Values.lotusStsLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
  {{- range $key, $value := .Values.lotusServiceAnnotations }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- range $key, $value := .Values.lotusStsLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      name: tcp-api
    - protocol: TCP
      port: 2346
      targetPort: 2346
      name: gateway
    {{- if .Values.enableLotusP2pPort }}
    - protocol: TCP
      port: 1235
      targetPort: 1235
      name: p2p
    {{- end}}
  {{- end}}
