{{- if .Values.StateDiff.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statediff-service
spec:
  type: ClusterIP 
  selector:
    app: lotus-node-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 33333
      name: rpc
{{- end }}
