{{- if .Values.Lotus.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lotus-service
  labels:
    app: lotus-node-app
  {{- if .Values.Lotus.service.annotations.default }}
  annotations:
  {{- range $key, $value := .Values.Lotus.service.annotations.default }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.Lotus.service.annotations.custom }}
  {{- range $key, $value := .Values.Lotus.service.annotations.custom }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      name: tcp-api
  {{- if .Values.Lotus.env.custom.INFRA_LOTUS_GATEWAY }}
    - protocol: TCP
      port: 2346
      targetPort: 2346
      name: gateway
  {{- end}}
{{- end }}
