{{- if .Values.Lotus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lotus-service
  labels:
    app: lotus-node-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1234"
    prometheus.io/path: /debug/metrics
spec:
  type: ClusterIP
  selector:
    app: lotus-node-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      name: tcp-api
{{- end }}
