{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "chart.allLabels" . | nindent 4 }}
{{- end }}

{{- if and .Values.persistence.enabled .Values.persistence.autoResizer.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role-resizer
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["patch"]
    resourceNames:
      {{- range untilStep 0 (.Values.replicaCount | int) 1 }}
      - vol-{{ $.Values.client }}-{{ $.Release.Name }}-{{ $.Values.client }}-{{ . }}
      {{- if $.Values.ipfs.enabled }}
      - vol-ipfs-{{ $.Release.Name }}-{{ $.Values.client }}-{{ . }}
      {{- end }}
      {{- end }}
  - apiGroups: ["apps",""]
    resources: ["statefulsets","pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
    resourceNames:
      {{- range untilStep 0 (.Values.replicaCount | int) 1 }}
      - {{ $.Release.Name }}-{{ $.Values.client }}-{{ . }}
      {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding-resizer
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }} 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role-resizer
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if and .Values.ipfs.enabled .Values.persistence.snapshots.uploadToIpfs.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role-exec
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    resourceNames:
      {{- range untilStep 0 (.Values.replicaCount | int) 1 }}  
      - {{ $.Release.Name }}-{{ $.Values.client }}-{{ . }}
      {{- end }}
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding-exec
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }} 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role-exec
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if and .Values.persistence.enabled .Values.persistence.snapshots.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role 
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["list", "describe", "patch", "replace", "get", "delete", "create"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }} 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
