{{- if .Values.createMirroredService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mirrored-lotus-service
  labels:
    app: lotus-node-app
  annotations:
  {{- range $key, $value := .Values.lotusServiceAnnotations }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
  {{- range $key, $value := .Values.mirroredServiceSelectors }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      name: tcp-api
    {{- if .Values.lotusEnv.INFRA_LOTUS_GATEWAY }}
    - protocol: TCP
      port: 2346
      targetPort: 2346
      name: gateway
    {{- end}}
{{- end }}
