{{- if .Values.createServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "chart.labels" . | nindent 4 }}
{{- end }}

---
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: Role*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-role-resizer*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*rules:*/}}
{{/*- apiGroups: [""]*/}}
{{/*  resources: ["persistentvolumeclaims"]*/}}
{{/*  verbs: ["get"]*/}}
{{/*- apiGroups: [""]*/}}
{{/*  resources: ["persistentvolumeclaims"]*/}}
{{/*  verbs: ["patch"]*/}}
{{/*  resourceNames:*/}}
{{/*{{- range untilStep 0 (.Values.replicaCount|int) 1 }}*/}}
{{/*    - vol-lotus-{{ $.Release.Name }}-lotus-{{ . }}*/}}
{{/*{{- if $.Values.IPFS.enabled }}*/}}
{{/*    - vol-ipfs-{{ $.Release.Name }}-lotus-{{ . }}*/}}
{{/*{{- end }}*/}}
{{/*{{- end }}*/}}
{{/*- apiGroups: ["apps",""]*/}}
{{/*  resources: ["statefulsets","pods"]*/}}
{{/*  verbs: ["get"]*/}}
{{/*- apiGroups: [""]*/}}
{{/*  resources: ["pods/exec"]*/}}
{{/*  verbs: ["create"]*/}}
{{/*  resourceNames:*/}}
{{/*{{- range untilStep 0 (.Values.replicaCount|int) 1 }}*/}}
{{/*    - {{ $.Release.Name }}-lotus-{{ . }}*/}}
{{/*{{- end }}*/}}

---
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: RoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-binding-resizer*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*subjects:*/}}
{{/*- kind: ServiceAccount*/}}
{{/*  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }} */}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*roleRef:*/}}
{{/*  kind: Role*/}}
{{/*  name: {{ .Release.Name }}-role-resizer*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}

{{- if .Values.useIpfs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role-exec
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  resourceNames:
  {{- range untilStep 0 (.Values.lotusStatefulSetReplicas|int) 1 }}  
    - {{ $.Release.Name }}-lotus-{{ . }}
  {{- end }}
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding-exec
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role-exec
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- if .Values.createServiceRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
