apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-lotus 
  labels:
    app: lotus-node-app
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "chart.servicename" . }}
  selector:
    matchLabels:
      app: lotus-node-app
  template:
    metadata:
      labels:
        app: lotus-node-app
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
{{- if .Values.securityContext.runAsNonRoot }}
      securityContext:
        # The image runs as uid 1000 by default, and needs to be able to write to
        # the persistent volume to be able to start.
        fsGroup: {{ .podSecurityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
      volumes:
{{- if .Values.secretVolume.enabled }}
        - name: lotus-secret-vol
          secret:
            secretName: {{ .Release.Name }}-lotus-secret
            defaultMode: 384 # permission 0600
{{- end }}
      initContainers:
{{- if .Values.secretVolume.enabled }}
      - name: api-keys
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["mkdir -p /lotus/keystore; cp /secret/privatekey /lotus/keystore/MF2XI2BNNJ3XILLQOJUXMYLUMU; cp /secret/token /lotus/token"]
        volumeMounts:
          - name: lotus-secret-vol
            mountPath: "/secret"
          - name: vol
            mountPath: /lotus
{{- end }}
{{- if .Values.init.import.enabled }}
      - name: import-wait
        image: debian:stable
        command: ["/bin/sh","-c"]
        args: ["until [ -f /chain/chain.car ] && [ ! -f /chain/chain.car.lock ]; do sleep 5; done"]
        volumeMounts:
          - name: {{ (index .Values.init.import.volume 0).name }}
            mountPath: /chain
{{- end }}
{{- if .Values.init.import.enabled }}
      - name: import-start
        image: {{ .Values.image.repository }}
        command: ["/bin/entrypoint","-i"]
        volumeMounts:
          - name: vol
            mountPath: /root/.lotus
          - name: {{ (index .Values.init.import.volume 0).name }}
            mountPath: /chain
{{- end }}
{{- if .Values.init.sync.enabled }}
      - name: sync-wait
        image: {{ .Values.image.repository }}
        command: ["/bin/entrypoint","-s"]
        volumeMounts:
          - name: vol
            mountPath: /root/.lotus
{{- end }}
      # - name: sanity
      #   image: busybox
      #   command: ["/bin/sh","-c"]
      #   args: ["chmod 600 /lotus/keystore/MF2XI2BNNJ3XILLQOJUXMYLUMU || chmod 600 /lotus/keystore/NRUWE4BSOAWWQ33TOQ || chmod 600 /lotus/token || :"]
      #   volumeMounts:
      #     - name: {{ .Release.Name }}-lotus-vol
      #       mountPath: /lotus
      containers:
{{- if .Values.Powergate.enabled }}
      - name: {{ .Chart.Name }}-powergate
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: textile/powergate
        livenessProbe:
          httpGet:
            port: 6002
          initialDelaySeconds: 90
          periodSeconds: 10
        ports:
        - containerPort: 8889
        - containerPort: 8888
        - containerPort: 6060
        - containerPort: 5002
        - containerPort: 6002
        env:
        - name: POWD_LOTUSHOST
          value: "/dns4/127.0.0.1/tcp/1234"
        - name: POWD_IPFSAPIADDR
          value: "/dns4/127.0.0.1/tcp/5001"
        - name: POWD_LOTUSTOKENFILE
          value: "/root/.lotus/token"
        - name: POWD_REPOPATH
          value: "/root/powergate/.powergate"
        volumeMounts:
          - name: vol-powergate
            mountPath: /root/powergate
          - name: vol
            mountPath: /root/.lotus
{{- end }}
{{- if .Values.IPFS.enabled }}
      - name: {{ .Chart.Name }}-ipfs
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: ipfs/go-ipfs
        livenessProbe:
          httpGet:
            path: /webui
            port: 5001
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 4001
        - containerPort: 5001
        - containerPort: 8080
          name: rpc
        volumeMounts:
          - name: vol-ipfs
            mountPath: /data/ipfs
{{- end }}
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        command: ["/bin/entrypoint","-d"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.IPFS.enabled }}
        env:
        - name: LOTUS_API_LISTENADDRESS
          value: "/ip4/0.0.0.0/tcp/1234/http"
        - name: LOTUS_CLIENT_USEIPFS
          value: "true"
        - name: LOTUS_CLIENT_IPFSUSEFORRETRIEVAL
          value: "true"
        - name: LOTUS_CLIENT_IPFSMADDR
          value: "/dns4/127.0.0.1/tcp/5001"
{{- end }}
        livenessProbe:
          httpGet:
            path: /debug/metrics
            port: api
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /debug/metrics
            port: api
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 1234
          name: api
        - containerPort: 1235
          name: p2p
        volumeMounts:
          - name: vol
            mountPath: /root/.lotus
        {{- if and (.Values.init.import.volume) (.Values.init.import.enabled) }}
          - name: {{ (index .Values.init.import.volume 0).name }}
            mountPath: /chain
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: vol
        {{- range $key, $value := .Values.persistence.lotus.annotations }}
            {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
            {{- range .Values.persistence.lotus.accessModes }}
            - {{ . | quote }}
            {{- end }}
        resources:
            requests:
                storage: {{ .Values.persistence.lotus.size | quote }}
        {{- if .Values.persistence.lotus.storageClassName }}
        {{- if (eq "-" .Values.persistence.lotus.storageClassName) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.lotus.storageClassName }}"
        {{- end }}
        {{- end }}
    - metadata:
        name: vol-ipfs
        {{- range $key, $value := .Values.persistence.ipfs.annotations }}
            {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
            {{- range .Values.persistence.ipfs.accessModes }}
            - {{ . | quote }}
            {{- end }}
        resources:
            requests:
                storage: {{ .Values.persistence.ipfs.size | quote }}
        {{- if .Values.persistence.ipfs.storageClassName }}
        {{- if (eq "-" .Values.persistence.ipfs.storageClassName) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.ipfs.storageClassName }}"
        {{- end }}
        {{- end }}
    - metadata:
        name: vol-powergate
        {{- range $key, $value := .Values.persistence.powergate.annotations }}
            {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
            {{- range .Values.persistence.powergate.accessModes }}
            - {{ . | quote }}
            {{- end }}
        resources:
            requests:
                storage: {{ .Values.persistence.powergate.size | quote }}
        {{- if .Values.persistence.powergate.storageClassName }}
        {{- if (eq "-" .Values.persistence.powergate.storageClassName) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.powergate.storageClassName }}"
        {{- end }}
        {{- end }}
  {{- end }}
